apiVersion: apps/v1
kind: Deployment
metadata: {{ include "service.http.metadata" . | nindent 2 }}
spec:
  replicas: {{ .Values.replicas | default 0 }}
  selector:
    matchLabels: {{ include "metadata.labels.name" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "metadata.labels.name" . | nindent 8 }}
      annotations:
        checksum/webconfig: {{ include (print $.Template.BasePath "/configmap-nginx.yml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yml") . | sha256sum }}
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ include "pvc.name" .}}
      - name: conf
        configMap: {{ include "http.configmap.metadata.name" . | nindent 10 }}
      - name: htpasswd
        emptyDir: {}
      initContainers:
      - name: htpasswd
        image: elswork/apache2-utils:latest
        envFrom:
        - secretRef: {{ include "metadata.name" . | nindent 12 }}
        command:
        - "/bin/sh"
        - "-c"
        args:
        - "htpasswd -cb /opt/htpasswd/htpasswd $(FTP_USER) $(FTP_PASS)"
        volumeMounts:
        - mountPath: "/opt/htpasswd"
          name: htpasswd
      containers:
      - name: web
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/www/vsftpd"
          name: storage
        - mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
          name: conf
        - mountPath: "/opt/htpasswd"
          name: htpasswd
        {{- include "deployment.image.pullpolicy" . | indent 8 -}}
{{- include "deployment.image.pullsecrets" . | indent 6 -}}