apiVersion: apps/v1
kind: Deployment
metadata: {{ include "metadata.common" . | nindent 2 }}
  annotations:
    checksum/webconfig: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
    checksum/config: {{ include (print $.Template.BasePath "/secrets.yml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicas | default 0 }}
  selector:
    matchLabels: {{ include "metadata.labels.name" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "metadata.labels.name" . | nindent 8 }}
    spec:
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: vsftpd
        image: {{ include "deployment.image" . }}
        ports:
        - containerPort: 21
        - containerPort: 20
        {{- include "deployment.image.pullpolicy" . | indent 8 -}}
{{- include "deployment.image.pullsecrets" . | indent 6 -}}