apiVersion: apps/v1
kind: Deployment
metadata: {{ include "metadata.common" . | nindent 2 }}
spec:
  replicas: {{ .Values.replicas | default 0 }}
  selector:
    matchLabels: {{ include "metadata.labels.name" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "metadata.labels.name" . | nindent 8 }}
    spec:
      containers:
      - name: vsftpd
        image: {{ include "deployment.image" . }}
        ports:
        - containerPort: 21
        - containerPort: 20
        {{- include "deployment.image.pullpolicy" . | indent 8 -}}
{{- include "deployment.image.pullsecrets" . | indent 6 -}}